### ISSUE TITLE
Socket closed and EOF exceptions when using IAM plugin

### ISSUE THREAD

**Issue by otbe** [awslabs/aws-advanced-jdbc-wrapper#618] opened 2023-08-28 07:08 UTC
### Describe the bug

Hello 👋

we tried to switch to this JDBC wrapper in order to get RDS IAM authentication working without the need for custom code for authentication handling. 

Our application is a Spring Boot app with tomcat db connection pooling. Connections from the pool seem to work quite fine. However we also bypass the pool in certain scenarios like `LISTEN` queries or usage of cursors. In these cases it does not work more often than it does. 

Our code looks like this (little bit simplified):

```java
// props are "wrapperPlugins=iam,driverMetaData;wrapperDriverName=PostgreSQL JDBC Driver;wrapperDialect=rds-pg;socketTimeout=0;connectTimeout=10;loginTimeout=10;tcpKeepAlive=true;" + username
var conn = DriverManager.getDriver("jdbc:aws-wrapper:postgresql://......")
          .connect("jdbc:aws-wrapper:postgresql://......", props)
          .unwrap(PgConnection.class)

try(var ps = conn.prepareStatement(PgConstants.LISTEN_SQL) {
  ps.execue();
}

PGNotification[] notifications = conn.getNotifications(20000);
```

The last line is the one where we get `java.net.SocketException: Socket closed` for example (see current behaviour section).

### Expected Behavior

If I got it right after establishing the connection via IAM auth, there should be no difference anymore between a connection authentication via IAM or username/password right?
If this is true I would not expect these kind of exceptions.

### What plugins are used? What other connection properties were set?

iam,driverMetaData; props: see above

### Current Behavior

We get various different exceptions:

```
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:382)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:119)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:730)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:656)
	... 14 common frames omitted
Caused by: java.io.EOFException: null
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2119)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
```

```
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:253)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:332)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1465)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1069)
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:453)
	at org.postgresql.core.v3.QueryExecutorImpl.processNotifies(QueryExecutorImpl.java:789)
```

### Reproduction Steps

See above.

### Additional Information/Context

Our test setup just includes a single RDS Postgres instance, no aurora, no read replicas used, no multi az.

### The AWS Advanced JDBC Driver version used

2.2.3

### JDK version used

11 corretto

### Operating System and version

Debian

**Comment by crystall-bitquill** [comment] 2023-08-28 19:14
Hi @otbe,

Thank you for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

In the meantime, would you be able to provide the following information to help us with the investigation process?
1. Could you please provide driver logs? They can be enabled by adding the wrapperLoggerLevel to your props, i.e. "wrapperPlugins=iam,driverMetaData;wrapperDriverName=PostgreSQL JDBC Driver;wrapperDialect=rds-pg;socketTimeout=0;connectTimeout=10;loginTimeout=10;tcpKeepAlive=true;wrapperLoggerLevel=all;"
2. Are you able to execute the non-pgjdbc specific operations using the JDBC Wrapper instead of the PGJDBC connection? For instance:
```java
    var conn = DriverManager.getDriver("jdbc:aws-wrapper:postgresql://......")
        .connect("jdbc:aws-wrapper:postgresql://......", props);
    
    try(var ps = conn.prepareStatement(PgConstants.LISTEN_SQL) {
      ps.execue();
    }

    PGNotification[] notifications = conn.unwrap(PgConnection.class).getNotifications(20000);
```

Thank you!

**Comment by otbe** [comment] 2023-08-29 09:10
Hi @crystall-bitquill 

regarding 1.) yes, but it looks strange somehow. I can see a lot of logs like thisbefore 

```
s.a.awssdk.services.rds.RdsUtilities     : Generated RDS authentication token with expiration of 2023-08-29T09:20:40.539607Z
```

and when the code from above kicks in it looks like this

```
2023-08-29 11:06:02.684 DEBUG 9327 --- [      Finalizer] s.amazon.jdbc.ConnectionPluginManager    : Releasing resources.
2023-08-29 11:06:02.685 DEBUG 9327 --- [      Finalizer] software.amazon.jdbc.PluginServiceImpl   : Releasing resources.
2023-08-29 11:06:02.687  WARN 9327 --- [stance Listener] my.package.PgListener     : While waiting for Notifications

org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
```

It looks like something triggers a cleanup/release of resources when it shouldn't.

Regarding 2.)
Sadly not because its inside a library we use but I have the feeling it would solve this issue.

**Comment by crystall-bitquill** [comment] 2023-09-16 07:18
Hi @otbe,

To update you, I haven't been able to reproduce this error yet.

I set up a simple Spring application using Tomcat connection pooling, and also set up a method to fetch another connection separately and to execute the code in the simplified snippet you provided. I used the connection properties you mentioned and connected to a single RDS PostgreSQL node, with the engine version being 15.3.

You mentioned that this error does not happen all the time but occurs more often than not, so I ran the relevant code on repeat and did not get any socket closed errors.

Is there anything in the setup I've described that is missing or seems incorrect? Are there any other operations occurring at the same time?

**Comment by otbe** [comment] 2023-09-16 09:03
Hi @crystall-bitquill 

I was able to create a simple repro over here https://github.com/otbe/aws-jdbc-wrapper-repo
If you run `com.example.demo.DemoApplicationTests#failingTest` it should fail with the behaviour from above. Depending on your machine you might have to play a little bit with the number of iterations.

It seems unrelated to which database is used (in my repro its just an ordinary pg via testcontaienrs). It just depends on the memory pressure/gc activities. 

The official postgresql jdbc driver also moved away from finalize, see https://jdbc.postgresql.org/changelogs/2023-03-17-42.6.0-release/.

**Comment by crystall-bitquill** [comment] 2023-09-20 04:45
Hi @otbe,

Thank you for providing a repro! You were right about the ConnectionWrapper being garbage collected.

You mentioned this code being inside of a library, but just to confirm, it is not possible to keep a reference to the connection provided by the AWS JDBC Driver? Similar to this:

```java
try (var wrapperConnection = DriverManager.getConnection(url);
     var pgConnection = wrapperConnection.unwrap(PgConnection.class)) {
    // execute operations
}
```

The AWS JDBC Driver will only provide generic JDBC connections, and unreferenced connections will be garbage collected. Therefore, if it is not possible to keep a reference to the connection provided by the driver, you unfortunately may need to consider whether this driver is the most fitting option for you. I understand you wanted to avoid using custom code for authentication handling, but if the IAM Authentication plugin was the only feature being used, it may be worth looking into. There is an example on how to generate authentication tokens [here](https://docs.aws.amazon.com/code-library/latest/ug/rds_example_rds_GenerateRDSAuthToken_section.html), and we also generate tokens similarly inside the [IAM Authentication Plugin](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/plugin/IamAuthConnectionPlugin.java).

Lastly, you mentioned that the official PostgreSQL JDBC Driver is moving away from finalize. The changes you linked use `PhantomReferences`, which from my understanding are used to perform cleanup actions. In this case where the goal is to keep the ConnectionWrapper open without triggering any cleanup, `PhantomReferences` does not seem suitable for this situation.

**Comment by crystall-bitquill** [comment] 2024-02-14 23:45
Hi @otbe,

We'll be closing this ticket now as it has been some time since there's been any updates and we will not be issuing code changes for this issue. Please feel free to reach out again if you have other questions or concerns.

Thank you!

**Closed by crystall-bitquill** 2024-02-14 23:45 UTC
Labels: bug
