### ISSUE TITLE
v1.0.2 cannot connect to an RDS PostgreSQL instance

### ISSUE THREAD

**Issue by renedewaele** [awslabs/aws-advanced-jdbc-wrapper#399] opened 2023-04-21 05:47 UTC
### Describe the bug

When any connection is created I'm getting the following error:

```
PSQLException
ERROR: function aurora_replica_status() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 35
```

### Expected Behavior

Same behavior as with v1.0.1 of the wrapper.

### What plugins are used? What other connection properties were set?

None

### Current Behavior

```
org.postgresql.util.PSQLException: ERROR: function aurora_replica_status() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 35
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
    at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
    at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:246)
    at software.amazon.jdbc.hostlistprovider.AuroraHostListProvider.queryForTopology(AuroraHostListProvider.java:349)
    at software.amazon.jdbc.hostlistprovider.AuroraHostListProvider.getTopology(AuroraHostListProvider.java:262)
    at software.amazon.jdbc.hostlistprovider.AuroraHostListProvider.refresh(AuroraHostListProvider.java:478)
    at software.amazon.jdbc.PluginServiceImpl.refreshHostList(PluginServiceImpl.java:320)
    at software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.connect(FailoverConnectionPlugin.java:795)
    at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:348)
    at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:275)
    at software.amazon.jdbc.ConnectionPluginManager.lambda$null$1(ConnectionPluginManager.java:275)
    at software.amazon.jdbc.plugin.AuroraConnectionTrackerPlugin.connect(AuroraConnectionTrackerPlugin.java:96)
    at software.amazon.jdbc.ConnectionPluginManager.lambda$connect$4(ConnectionPluginManager.java:348)
    at software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$2(ConnectionPluginManager.java:275)
    at software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:253)
    at software.amazon.jdbc.ConnectionPluginManager.connect(ConnectionPluginManager.java:345)
    at software.amazon.jdbc.wrapper.ConnectionWrapper.init(ConnectionWrapper.java:131)
    at software.amazon.jdbc.wrapper.ConnectionWrapper.<init>(ConnectionWrapper.java:85)
    at software.amazon.jdbc.ds.AwsWrapperDataSource.createConnectionWrapper(AwsWrapperDataSource.java:164)
    at software.amazon.jdbc.ds.AwsWrapperDataSource.getConnection(AwsWrapperDataSource.java:134)
    at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
    at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
    at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
    at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
```

### Reproduction Steps

Create a new maven project and make sure to include the following dependencies:

```xml
<dependency>
    <groupId>org.postgresql</groupId>
    <artifactId>postgresql</artifactId>
    <version>42.6.0</version>
</dependency>

<dependency>
    <groupId>software.amazon.jdbc</groupId>
    <artifactId>aws-advanced-jdbc-wrapper</artifactId>
    <version>1.0.2</version>
</dependency>
```

Add the following java file and run against an **RDS** instance running Postgres 15.2 (**i.e. not an Aurora cluster**).

### ReproduceRdsConnectionIssue.java
```java
import software.amazon.jdbc.ds.AwsWrapperDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;

public class ReproduceRdsConnectionIssue {

    public static void main(String[] args) throws Exception {
        AwsWrapperDataSource ds = getDataSource();
        try (final Connection conn = ds.getConnection("myUser", "myPassword");
             final Statement statement = conn.createStatement();
             final ResultSet rs = statement.executeQuery("SELECT 1")) {
            if (rs.next()) {
                System.out.println("Got " + rs.getInt(1));
            }
        }
    }

    static AwsWrapperDataSource getDataSource() {
        AwsWrapperDataSource ds = new AwsWrapperDataSource();
        ds.setJdbcProtocol("jdbc:postgresql:");
        ds.setDatabasePropertyName("databaseName");
        ds.setServerPropertyName("serverName");
        ds.setPortPropertyName("port");
        ds.setTargetDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");
        Properties targetDataSourceProps = new Properties();
        targetDataSourceProps.setProperty("serverName", "myServerName");
        targetDataSourceProps.setProperty("databaseName", "myDatabaseName");
        targetDataSourceProps.setProperty("port", "myPort");
        ds.setTargetDataSourceProperties(targetDataSourceProps);
        return ds;
    }
}
```

### Additional Information/Context

- Postgres 15.2 on RDS
- Java 17
- Used HikariCP for database pooling but don't think it matters

### The AWS Advanced JDBC Driver version used

1.0.2

### JDK version used

17

### Operating System and version

Ubuntu

**Comment by aaronchung-bitquill** [comment] 2023-04-21 17:00
Hi @renedewaele 

Thank you for reaching out and raising this issue. Also thank you for including your  stack trace, maven dependencies, and even a code snippet. It is much appreciated! 

We'll be taking a look at this and keep you updated as we investigate. 

In the meantime, would you confirm if you are using a RDS Aurora PostrgeSQL database or just a RDS PostreSQL database? 

Thank you for your patience!

**Comment by renedewaele** [comment] 2023-04-21 18:08
@aaronchung-bitquill just RDS PostgreSQL sans Aurora

**Comment by vpavic** [comment] 2023-04-21 19:30
Same issue here after upgrading to `1.0.2` - also using plain RDS PostgreSQL.

**Comment by crystall-bitquill** [comment] 2023-04-27 19:01
Hi @renedewaele and @vpavic,

I believe this issue is caused by the connection plugins that have been enabled by default, which would be the Failover, Host Monitoring and Aurora Connection Tracker plugins. These plugins were not enabled by default in versions prior to 1.0.2.

If you are connecting to plain RDS PostgreSQL, you will need to disable plugins that query for information about Aurora nodes. This can be done by setting the `wrapperPlugins` property to an empty string.

Please let us know if this works for you or if you have any other issues.

Thank you!

**Comment by renedewaele** [comment] 2023-05-10 10:02
Hi @crystall-bitquill,

Thanks for your answer, makes a lot sense and will try it out. 

The main reason why I'm using the connection wrapper is to enable faster failover. Do I still get benefit from the wrapper if I disable all connection plugins? Are all these connection plugins Aurora only or are some also relevant for plain RDS as well?

There's not a lot of documentation what the wrapper does when connecting to plain RDS instances. Perhaps it would be good to add this info in the readme. 

In any case thanks again!

**Comment by crystall-bitquill** [comment] 2023-05-10 16:47
> Judging by https://github.com/awslabs/aws-advanced-jdbc-wrapper/discussions/216, there are no failover enhancements with plain RDS.

This is correct. There are no failover benefits with plain RDS, but you could still use the IAM Authentication or AWS Secrets Manager connection plugins.

> There's not a lot of documentation on what the wrapper does when connecting to plain RDS instances. Perhaps it would be good to add this info in the readme.

Thank you for the suggestion!

**Comment by hsuamz** [comment] 2023-05-16 18:19
Thanks @renedewaele, we'll be improving our documentation to make this clearer. We'll be closing this issue and please feel free to reach out to us if you have any further questions regarding the driver.

**Closed by hsuamz** 2023-05-16 18:19 UTC
Labels: documentation, question
