### ISSUE TITLE
XA datasource support

### ISSUE THREAD

**Issue by flauschie** [awslabs/aws-advanced-jdbc-wrapper#511] opened 2023-07-03 02:49 UTC
### Describe the feature

I don't know whether this is just a documentation issue or missing functionality. 

However, I haven't found any reference on how to configure an XA datasource?

I reckon that in-code you could specify this here:
* ds.addDataSourceProperty("targetDataSourceClassName", "com.mysql.cj.jdbc.MysqlXADataSource");

However, we are using Wildly, and you can't specify a custom `targetDataSourceClassName` property in the standalone.xml of the server.

Example:
```
                    <driver name="mysql" module="com.mysql">
                        <driver-class>software.amazon.jdbc.driver</driver-class>
                        <xa-datasource-class>???</xa-datasource-class>
                    </driver>
```

Note: We tried the AWS JDBC Driver fro MySQL, but it produces failures in XA mode that haven't been fixed for ages. 
Thus the wrapper could be a viable alternative.

### Use Case

Support for distributed transactions.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.x

### JDK version used

JDK 11

### Operating System and version

Amazon Linux 2

**Comment by karenc-bq** [comment] 2023-07-06 23:09
Hi @flauschie, unfortunately the wrapper driver does not support XA Datasources by design. Target drivers do not expose the internal connection when establishing an XA-enabled connection, thus the AWS Driver cannot integrate the XA-enabled connection into the plugin pipeline.

Sorry for the inconvenience.

**Comment by karenc-bq** [comment] 2023-07-20 22:39
Hi @flauschie, we will be closing this issue now, please don't hesitate to reach out again should any other issues arise.

**Closed by karenc-bq** 2023-07-20 22:39 UTC
Labels: enhancement

**Comment by mwgreen** [comment] 2023-09-13 18:56
2 things:
1.  The docs say "drop in replacement".  This makes that not-true
2. This is not in the 'known limitations' document

This is very much needed, BTW

**Comment by mbialozor** [comment] 2024-07-17 10:50
@karenc-bq, so, if we need to use XA Datasources (removing this requirement requires changing the architecture of our apps - will be done in the future, but it's not trivial) we just can't use the Wrapper, am I right? I mean we should stick to original https://jdbc.postgresql.org/ driver, right? Any other options here?

**Comment by davecramer** [comment] 2024-07-30 09:41
@flauschie I'll spend some time looking into this.

**Comment by mbialozor** [comment] 2024-08-12 14:43
> @flauschie I'll spend some time looking into this.

Good morning @davecramer. Do you have any thoughts on this?

**Comment by s4a-mjarosz** [comment] 2024-09-10 10:35
Hi @davecramer. Any thought on this?

@mwgreen, any extra update from your side?

**Comment by kanwhoa** [comment] 2025-05-23 04:28
Hi,

Jumping in on this, naively, is it not possible to just subclass [XADatasource](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/javax/sql/XADataSource.html) which then proxies it's methods straight through the underlying XA driver class.

The only issue then is custom properties which are provided by each XA driver. If we assume that for the most part, this will be used in infrastructure scenarios, i.e. application servers etc, then most of the getter methods are irrelevant because the application server will not know how to call those, or even care about the response.

The only real challenge is the setter methods which are used to configure the underlying XA datasource. A nasty solution for this would be to create a setProxyProperty method, which takes a set of URL encoded proxy keys/values.

For example, in WildFly, the configuration for MariaDB might look like:

```
--xa-datasource-properties={"Url"=>"jdbc:mariadb://host:port/schema"}
```

With the proxied variant, it might look like:
```
--xa-datasource-properties={"ProxyProperty"=>"Url=jdbc%3Aaws-wrapper%3Amariadb%3A%2F%2Fhost%3Aport%2Fschema&..."}
```

These could then be set by reflection. This would at least provide a workable proxy, at least without having to mirror each XA data source implementation.
