### ISSUE TITLE
Failover mode with efm2 - fails to connect to Aurora RDS cluster

### ISSUE THREAD

**Issue by beingaryan** [awslabs/aws-advanced-jdbc-wrapper#850] opened 2024-01-23 14:56 UTC
### Describe the bug

I am encountering an issue with the AWS wrapper when attempting to connect to an RDS instance. 

RDS_CLUSTER_URL: https://jdbc:aws-wrapper:mariadb:<cluster_url>:<port_no>/<databasename>?wrapperPlugins=failover,efm2

### Expected Behavior

Connection should have been established successfully, and data should have been fetched.

### What plugins are used? What other connection properties were set?

failover,efm2

### Current Behavior

The error message is as follows:

`Failed to initialize pool: ConnectionStringHostListProvider does not support getHostRole\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)\n\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)\n\tat org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1166)\n\tat org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:940)\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738)\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:316)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)\n\tat `

### Reproduction Steps

Relevant properties for Springboot

`driverClassName: software.amazon.jdbc.Driver\n
platform: mysql`

Using mysql-connector and aws-advanced-jdbc-wrapper

### Possible Solution

NA

### Additional Information/Context

NA

### The AWS Advanced JDBC Driver version used

2.3.2

### JDK version used

java version "17.0.2" 2022-01-18 LTS Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)

### Operating System and version

Container

**Comment by crystall-bitquill** [comment] 2024-01-25 00:58
Hi @beingaryan,

Thanks for reaching out and raising this issue.

Are you using an RDS MySQL cluster or an Aurora MySQL cluster? Can you please verify which database dialect has been detected by enabling logs? In the logs, the database dialect should looks similar to this:
```
s.amazon.jdbc.dialect.DialectManager     : Current dialect: aurora-mysql, software.amazon.jdbc.dialect.AuroraMysqlDialect, canUpdate: false
```

We currently suspect this is being caused by the same issue resolved in PR #836. This fix was released recently in v2.3.3. Could you please try out the new version and see if it resolves your issue?

Thank you!

**Closed** 2024-03-06 22:44 UTC
Labels: bug, question
